"""ReportLab-based PDF renderer. Pure function: ReportData -> bytes."""
import io
import logging
from datetime import datetime

import matplotlib
matplotlib.use("Agg")  # MUST be set before importing pyplot
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.report import ReportData

logger = logging.getLogger(__name__)

PAGE_MARGIN = 1.5 * cm

styles = getSampleStyleSheet()
H1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=18, spaceAfter=10, textColor=colors.HexColor("#1a3a5c"))
H2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=6, textColor=colors.HexColor("#1a3a5c"))
H3 = ParagraphStyle("H3", parent=styles["Heading3"], fontSize=11, spaceAfter=4, textColor=colors.HexColor("#444444"))
BODY = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9.5, leading=13)
SMALL = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
KPI_LABEL = ParagraphStyle("KpiLabel", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=1)
KPI_VALUE = ParagraphStyle("KpiValue", parent=styles["Normal"], fontSize=14, alignment=1, textColor=colors.HexColor("#1a3a5c"))


def render_report_pdf(data: ReportData) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN, bottomMargin=PAGE_MARGIN,
        title=f"{data.project.name} — {data.period.label}",
        author=data.generated_by,
    )

    story: list = []
    _cover(story, data)
    _executive_summary(story, data)
    if data.progress:
        _progress(story, data)
    if data.performance:
        _performance(story, data)
    if data.financial:
        _financial(story, data)
    if data.manpower:
        _manpower(story, data)
    if data.equipment:
        _equipment(story, data)
    if data.materials:
        _materials(story, data)
    if data.weather:
        _weather(story, data)
    if data.tasks:
        _tasks(story, data)
    if data.look_ahead:
        _look_ahead(story, data)
    if data.daily_logs:
        _daily_logs(story, data)
    if data.risk:
        _risk(story, data)
    _footer(story, data)

    doc.build(story, onFirstPage=_page_decoration, onLaterPages=_page_decoration)
    return buf.getvalue()


def _page_decoration(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(PAGE_MARGIN, 1 * cm, f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    canvas.drawRightString(A4[0] - PAGE_MARGIN, 1 * cm, f"Page {doc.page}")
    canvas.restoreState()


def _money(v: float) -> str:
    return f"{v:,.2f}"


def _pct(v: float | None) -> str:
    return f"{v:.1f}%" if v is not None else "—"


def _cover(story: list, data: ReportData) -> None:
    story.append(Paragraph(data.project.name, H1))
    story.append(Paragraph(f"<b>{data.period.label}</b>", H2))
    story.append(Spacer(1, 0.4 * cm))

    rows = [
        ["Client", data.project.client_name or "—", "Status", data.project.status or "—"],
        ["Location", data.project.location or "—", "Owner / PM", data.project.owner_name or "—"],
        ["Planned start", _date(data.project.planned_start), "Planned end", _date(data.project.planned_end)],
        ["Contract value", _money(data.project.contract_value), "Cut-off date", _date(data.period.cut_off)],
        ["Timezone", data.period.project_timezone, "Generated by", data.generated_by],
    ]
    t = Table(rows, colWidths=[3.5 * cm, 5.5 * cm, 3.5 * cm, 5 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f0f4f8")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5 * cm))


def _kpi_card(label: str, value: str, color: str = "#1a3a5c") -> Table:
    style = ParagraphStyle("Kpi", parent=KPI_VALUE, textColor=colors.HexColor(color))
    inner = Table(
        [[Paragraph(value, style)], [Paragraph(label, KPI_LABEL)]],
        colWidths=[3.6 * cm], rowHeights=[0.9 * cm, 0.6 * cm],
    )
    inner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#dde3ea")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return inner


def _executive_summary(story: list, data: ReportData) -> None:
    s = data.summary
    story.append(Paragraph("Executive Summary", H2))

    spi_color = "#16a34a" if s.spi >= 0.95 else ("#f59e0b" if s.spi >= 0.85 else "#dc2626")
    cpi_color = "#16a34a" if s.cpi >= 0.95 else ("#f59e0b" if s.cpi >= 0.85 else "#dc2626")
    risk_color = {"low": "#16a34a", "medium": "#f59e0b", "high": "#ea580c", "critical": "#dc2626"}.get(
        (s.risk_level or "").lower(), "#1a3a5c"
    )

    cards = [[
        _kpi_card("Progress", _pct(s.progress.cumulative)),
        _kpi_card("Planned", _pct(s.planned_progress)),
        _kpi_card("SPI", f"{s.spi:.2f}", color=spi_color),
        _kpi_card("CPI", f"{s.cpi:.2f}", color=cpi_color),
        _kpi_card("Risk", (s.risk_level or "—").upper(), color=risk_color),
    ]]
    grid = Table(cards, colWidths=[3.6 * cm] * 5)
    grid.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    story.append(grid)
    story.append(Spacer(1, 0.3 * cm))

    rows = [
        ["", "This period", "Project to date"],
        ["Progress", _pct(s.progress.period), _pct(s.progress.cumulative)],
        ["Budget spent", "—", _money(s.budget.budget_spent)],
        ["Budget remaining", "—", _money(s.budget.remaining)],
        ["Budget received", "—", _money(s.budget.total_received)],
        ["Tasks completed", str(s.task_counts.get("completed", 0)), f"{s.task_counts.get('completed', 0)}/{s.task_counts.get('total', 0)}"],
        ["Tasks overdue", "—", str(s.task_counts.get("overdue", 0))],
        ["Schedule variance (days)", "—", str(s.schedule_variance_days)],
        ["Days elapsed / remaining", "—", f"{s.days_elapsed} / {s.days_remaining}"],
        ["Weather days lost", str(s.weather_days_lost), "—"],
    ]
    story.append(_kv_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _progress(story: list, data: ReportData) -> None:
    p = data.progress
    story.append(Paragraph("Progress", H2))
    if p.s_curve and len(p.s_curve) >= 2:
        chart = _s_curve_chart(p)
        if chart:
            story.append(chart)
            story.append(Spacer(1, 0.2 * cm))
    else:
        story.append(Paragraph(
            "<i>S-curve will populate as more progress snapshots are captured. "
            "Each report download captures a snapshot.</i>", SMALL,
        ))
        story.append(Spacer(1, 0.2 * cm))
    rows = [
        ["Progress this period", _pct(p.progress_this_period.period)],
        ["Cumulative progress", _pct(p.progress_this_period.cumulative)],
        ["Days elapsed", str(p.days_elapsed)],
        ["Days remaining", str(p.days_remaining)],
        ["Schedule variance (days)", str(p.schedule_variance_days)],
    ]
    story.append(_kv_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _s_curve_chart(p) -> Image | None:
    try:
        fig, ax = plt.subplots(figsize=(7, 3))
        dates = [pt.date for pt in p.s_curve]
        actual = [pt.actual_progress for pt in p.s_curve]
        ax.plot(dates, actual, marker="o", color="#1a3a5c", label="Actual %")
        if any(pt.planned_progress is not None for pt in p.s_curve):
            planned = [pt.planned_progress or 0 for pt in p.s_curve]
            ax.plot(dates, planned, linestyle="--", color="#94a3b8", label="Planned %")
        ax.set_ylabel("Progress %")
        ax.set_ylim(0, 100)
        ax.grid(True, alpha=0.3)
        ax.legend(loc="lower right", fontsize=8)
        ax.tick_params(axis="x", rotation=30, labelsize=7)
        ax.tick_params(axis="y", labelsize=8)
        fig.tight_layout()
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=150)
        plt.close(fig)
        buf.seek(0)
        img = Image(buf, width=16 * cm, height=6.5 * cm)
        return img
    except Exception as e:
        logger.exception("Failed to render S-curve: %s", e)
        return None


def _performance(story: list, data: ReportData) -> None:
    e = data.performance
    story.append(Paragraph("Earned Value Performance", H2))
    rows = [
        ["Metric", "Value", "Status"],
        ["SPI (Schedule)", f"{e.spi:.3f}", e.spi_status],
        ["CPI (Cost)", f"{e.cpi:.3f}", e.cpi_status],
        ["Planned Value (PV)", _money(e.planned_value), ""],
        ["Earned Value (EV)", _money(e.earned_value), ""],
        ["Actual Cost (AC)", _money(e.actual_cost), ""],
    ]
    story.append(_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _financial(story: list, data: ReportData) -> None:
    f = data.financial
    story.append(Paragraph("Financial", H2))
    rows = [
        ["", "This period", "Cumulative"],
        ["Manpower cost", _money(f.manpower_cost.period), _money(f.manpower_cost.cumulative)],
        ["Material cost", _money(f.material_cost.period), _money(f.material_cost.cumulative)],
        ["Equipment cost", _money(f.equipment_cost.period), _money(f.equipment_cost.cumulative)],
        ["Incoming budget", _money(f.incoming_budget.period), _money(f.incoming_budget.cumulative)],
        ["Burn rate / day", _money(f.burn_rate_per_day), "—"],
    ]
    story.append(_table(rows))
    story.append(Spacer(1, 0.2 * cm))
    bd = [
        ["Budget", "Amount"],
        ["Total budget", _money(f.budget.total_budget)],
        ["Spent", _money(f.budget.budget_spent)],
        ["Received", _money(f.budget.total_received)],
        ["Remaining", _money(f.budget.remaining)],
    ]
    story.append(_table(bd))
    story.append(Spacer(1, 0.4 * cm))


def _manpower(story: list, data: ReportData) -> None:
    l = data.manpower
    story.append(Paragraph("Manpower", H2))
    rows = [
        ["", "This period", "Cumulative"],
        ["Total hours", f"{l.total_hours.period:,.1f}", f"{l.total_hours.cumulative:,.1f}"],
        ["Total cost", _money(l.total_cost.period), _money(l.total_cost.cumulative)],
    ]
    story.append(_table(rows))
    story.append(Spacer(1, 0.2 * cm))
    if l.by_trade:
        trade_rows = [["Trade", "Hours (period)", "Hours (cumulative)"]]
        for trade, pc in sorted(l.by_trade.items(), key=lambda x: x[1].cumulative, reverse=True):
            trade_rows.append([trade, f"{pc.period:,.1f}", f"{pc.cumulative:,.1f}"])
        story.append(Paragraph("By trade", H3))
        story.append(_table(trade_rows))
        story.append(Spacer(1, 0.2 * cm))
    if l.histogram:
        chart = _manpower_chart(l)
        if chart:
            story.append(Paragraph("Daily manpower", H3))
            story.append(chart)
    story.append(Spacer(1, 0.4 * cm))


def _manpower_chart(l) -> Image | None:
    try:
        fig, ax = plt.subplots(figsize=(7, 2.8))
        dates = [e.date for e in l.histogram]
        totals = [e.total for e in l.histogram]
        ax.bar(dates, totals, color="#1a3a5c")
        ax.set_ylabel("Hours")
        ax.grid(True, alpha=0.3, axis="y")
        ax.tick_params(axis="x", rotation=30, labelsize=7)
        ax.tick_params(axis="y", labelsize=8)
        fig.tight_layout()
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=150)
        plt.close(fig)
        buf.seek(0)
        return Image(buf, width=16 * cm, height=6 * cm)
    except Exception as e:
        logger.exception("Failed to render manpower chart: %s", e)
        return None


def _equipment(story: list, data: ReportData) -> None:
    e = data.equipment
    story.append(Paragraph("Equipment", H2))
    summary = [
        ["", "This period", "Cumulative"],
        ["Hours used", f"{e.total_hours_used.period:,.1f}", f"{e.total_hours_used.cumulative:,.1f}"],
        ["Hours idle", f"{e.total_hours_idle.period:,.1f}", f"{e.total_hours_idle.cumulative:,.1f}"],
        ["Total cost", _money(e.total_cost.period), _money(e.total_cost.cumulative)],
        ["Overall utilization", f"{e.overall_utilization_pct:.1f}%", "—"],
    ]
    story.append(_table(summary))
    story.append(Spacer(1, 0.2 * cm))
    if e.by_equipment:
        rows = [["Equipment", "Used (h)", "Idle (h)", "Util %", "Top idle reason"]]
        for u in e.by_equipment[:15]:
            top_reason = u.top_idle_reasons[0]["reason"] if u.top_idle_reasons else "—"
            rows.append([u.name, f"{u.hours_used:,.1f}", f"{u.hours_idle:,.1f}", f"{u.utilization_pct:.1f}%", top_reason])
        story.append(_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _materials(story: list, data: ReportData) -> None:
    m = data.materials
    story.append(Paragraph("Materials", H2))
    rows = [["Material", "Quantity", "Unit", "Cost"]]
    for item in m.top_by_cost[:15]:
        rows.append([item["name"], f"{item['quantity']:,.2f}", item.get("unit") or "—", _money(item["cost"])])
    if len(rows) == 1:
        story.append(Paragraph("<i>No material entries in this period.</i>", SMALL))
    else:
        story.append(_table(rows))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        f"Total material cost — period: <b>{_money(m.total_cost.period)}</b>, "
        f"cumulative: <b>{_money(m.total_cost.cumulative)}</b>", BODY,
    ))
    story.append(Spacer(1, 0.4 * cm))


def _weather(story: list, data: ReportData) -> None:
    w = data.weather
    story.append(Paragraph("Weather Impact", H2))
    rows = [
        ["Days in period", str(w.days_in_period)],
        ["Weather days lost", str(w.weather_days_lost)],
    ]
    for k, v in w.weather_breakdown.items():
        rows.append([f"  — {k}", str(v)])
    story.append(_kv_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _tasks(story: list, data: ReportData) -> None:
    t = data.tasks
    story.append(Paragraph("Tasks", H2))
    story.append(Paragraph(f"Completed in period ({len(t.completed_in_period)})", H3))
    story.append(_task_table(t.completed_in_period))
    story.append(Paragraph(f"Started in period ({len(t.started_in_period)})", H3))
    story.append(_task_table(t.started_in_period))
    if t.overdue:
        story.append(Paragraph(f"<font color='#dc2626'>Overdue ({len(t.overdue)})</font>", H3))
        story.append(_task_table(t.overdue))
    story.append(Spacer(1, 0.4 * cm))


def _task_table(tasks) -> Table | Paragraph:
    if not tasks:
        return Paragraph("<i>None</i>", SMALL)
    rows = [["Task", "Status", "Progress", "End"]]
    for tk in tasks[:25]:
        rows.append([tk.name, tk.status, _pct(tk.progress_percentage), _date(tk.end_date)])
    return _table(rows)


def _look_ahead(story: list, data: ReportData) -> None:
    la = data.look_ahead
    story.append(Paragraph(f"Look-ahead ({la.horizon_days} days)", H2))
    if not la.upcoming_tasks:
        story.append(Paragraph("<i>No upcoming tasks scheduled in this window.</i>", SMALL))
    else:
        rows = [["Task", "Status", "Start", "End"]]
        for tk in la.upcoming_tasks[:30]:
            rows.append([tk.name, tk.status, _date(tk.start_date), _date(tk.end_date)])
        story.append(_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _daily_logs(story: list, data: ReportData) -> None:
    d = data.daily_logs
    story.append(Paragraph("Daily Logs", H2))
    rows = [
        ["Total logs", str(d.log_count)],
        ["Total manpower hours", f"{d.total_manpower_hours:,.1f}"],
        ["Total equipment hours", f"{d.total_equipment_hours:,.1f}"],
        ["Equipment idle hours", f"{d.equipment_idle_hours:,.1f}"],
    ]
    for status, count in d.by_status.items():
        rows.append([f"  — {status}", str(count)])
    story.append(_kv_table(rows))
    story.append(Spacer(1, 0.4 * cm))


def _risk(story: list, data: ReportData) -> None:
    r = data.risk or {}
    story.append(Paragraph("Risk Assessment", H2))
    headline = [
        ["Risk level", str(r.get("level", "—")).upper()],
        ["Source", str(r.get("source", "—"))],
        ["Delay estimate (days)", str(r.get("delay_estimate_days", "—"))],
        ["Schedule deviation", f"{r.get('schedule_deviation', 0):.3f}"],
        ["Budget efficiency", f"{r.get('budget_efficiency', 0):.3f}"],
        ["Task completion rate", f"{r.get('task_completion_rate', 0):.3f}"],
    ]
    story.append(_kv_table(headline))
    story.append(Spacer(1, 0.4 * cm))


def _footer(story: list, data: ReportData) -> None:
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(
        f"<b>Approval status:</b> {data.approval.status} &nbsp;&nbsp; "
        f"<b>PM:</b> {data.approval.pm_name or '—'} &nbsp;&nbsp; "
        f"<b>Consultant:</b> {data.approval.consultant_name or '—'}",
        BODY,
    ))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        f"Data as of {_date(data.period.cut_off)} ({data.period.project_timezone}). "
        f"Report generated by {data.generated_by} at {data.generated_at.strftime('%Y-%m-%d %H:%M UTC')}.",
        SMALL,
    ))


def _table(rows: list[list[str]]) -> Table:
    t = Table(rows, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a3a5c")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _kv_table(rows: list[list[str]]) -> Table:
    t = Table(rows)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#dddddd")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _date(d) -> str:
    if not d:
        return "—"
    if isinstance(d, datetime):
        return d.strftime("%d %b %Y")
    return d.strftime("%d %b %Y")
