"""add rejection_reason and project tz/fiscal/week fields

Revision ID: 5a7b5d4f7467
Revises: f4a82c1e9d57
Create Date: 2026-05-06 01:40:22.243625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7b5d4f7467'
down_revision: Union[str, Sequence[str], None] = 'f4a82c1e9d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_logs', 'rejection_reason')
    # ### end Alembic commands ###
