"""add project tz/fiscal/week fields and progress snapshots

Revision ID: 6de7c29a0beb
Revises: a9fa1ced5131
Create Date: 2026-05-06 00:31:09.573825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de7c29a0beb'
down_revision: Union[str, Sequence[str], None] = 'a9fa1ced5131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('timezone', sa.String(length=64), server_default='Africa/Addis_Ababa', nullable=False))
    op.add_column('projects', sa.Column('fiscal_year_start_month', sa.Integer(), server_default='1', nullable=False))
    op.add_column('projects', sa.Column('week_starts_on', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'week_starts_on')
    op.drop_column('projects', 'fiscal_year_start_month')
    op.drop_column('projects', 'timezone')
    # ### end Alembic commands ###
