"""deploy_updates

Revision ID: 74ba722102ce
Revises: b467839cba72
Create Date: 2026-04-08 19:27:22.639125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74ba722102ce'
down_revision: Union[str, Sequence[str], None] = 'b467839cba72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.add_column('daily_logs', sa.Column('weather', sa.String(length=100), nullable=True))
    op.alter_column('daily_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('projects', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('planned_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('planned_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'planned_end_date')
    op.drop_column('projects', 'planned_start_date')
    op.drop_column('projects', 'location')
    op.alter_column('daily_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('daily_logs', 'weather')
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('payments_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###
