"""baseline

Revision ID: 924982cebe5a
Revises: d2f60a9b1c34
Create Date: 2026-05-10 20:26:58.887864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924982cebe5a'
down_revision: Union[str, Sequence[str], None] = 'd2f60a9b1c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_log_photos_log_id'), table_name='daily_log_photos')
    op.drop_index(op.f('ix_labor_id'), table_name='manpower')
    op.create_index(op.f('ix_manpower_id'), 'manpower', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manpower_id'), table_name='manpower')
    op.create_index(op.f('ix_labor_id'), 'manpower', ['id'], unique=False)
    op.create_index(op.f('ix_daily_log_photos_log_id'), 'daily_log_photos', ['log_id'], unique=False)
    # ### end Alembic commands ###
