"""add assigned_to to tasks

Revision ID: a9fa1ced5131
Revises: c7d2a4e91b38
Create Date: 2026-05-03 19:37:45.706996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9fa1ced5131'
down_revision: Union[str, Sequence[str], None] = 'c7d2a4e91b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###
